### ISSUE TITLE
Retain cycle due to TransactViewController being kept on memory

### ISSUE THREAD

**Issue by GianniCarlo** [atomicfi/atomic-transact-ios#1]
## Environment

* SDK version: 3.0.3
* Xcode 14.3.1 (run on simulator)

## Description

When we show the Atomic flow, and we either dismiss it or complete successfully, the `TransactViewController` never goes out of memory, and the `onCompletion` block from the SDK function is holding a strong reference to our class in charge of presenting the flow, and it's causing a retain cycle

```swift
public static func presentTransact(
  from source: UIViewController,
  config: AtomicTransact.AtomicConfig,
  environment: AtomicTransact.TransactEnvironment = .production,
  presentationStyle: UIModalPresentationStyle = .formSheet,
  onInteraction: ((AtomicTransact.TransactInteraction) -> ())? = nil,
  onDataRequest: ((AtomicTransact.TransactDataRequest) -> ())? = nil,
  onCompletion: ((AtomicTransact.TransactResponse) -> ())? = nil
)
```
From the memory graph from Xcode, after being dismissed, it looks like it's being held in memory by either some block passed to the NotificationCenter when registering an observer, or by something related to WebKit. If we show the Atomic flow multiple times, there will be different instances of `TransactViewController` stuck in memory

![Screenshot 2023-09-07 at 11 37 58](https://github.com/atomicfi/atomic-transact-ios/assets/14112819/fa5b5455-9f55-4512-86f3-90e7983f8806)

## Steps to reproduce

1. Show the Atomic flow via the SDK `Atomic.presentTransact(from:config:onCompletion)` while holding a strong reference to self on the onCompletion block
2. Dismiss, or complete the flow
3. Check Xcode Memory Graph

**Comment by sean-hill** [comment]
Hey @GianniCarlo ! Thanks for reporting this issue. It looks like it's probably related to [this](https://stackoverflow.com/questions/26383031/wkwebview-causes-my-view-controller-to-leak/26383032#26383032) issue with WKWebView which we use internally.

I'll give this solution a try next week and will let you know the results. Thanks!

**Comment by sean-hill** [comment]
@GianniCarlo it does look like we are removing the message script handlers, but only for iOS 14+.

```swift
private func removeWebViewMessageHandlers() {
    if #available(iOS 14.0, *) {
        webView.configuration.userContentController.removeAllScriptMessageHandlers()
    }
    
    observers.removeAll()
}

public override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    
    if isBeingDismissed {
        removeWebViewMessageHandlers()
    }
}
```

Is the issue you're seeing with the memory leak on a version of iOS less than 14?

**Comment by sean-hill** [comment]
@GianniCarlo we found an issue, and are working on a fix 👌

**Comment by GianniCarlo** [comment]
Hi @sean-hill ! sorry I took a while to respond, the iOS version is 16 (via Xcode's simulator iPhone 14). Regarding the fix, nice! let me know if I can help in any way

**Comment by sean-hill** [comment]
Hey @GianniCarlo wanted to give you an update. We fixed the issue, but we're currently adding some new features as well, so we're going to bundle it up together into a release, unless this is blocking you, then we can release it separately 😄

**Comment by GianniCarlo** [comment]
Hey @sean-hill ! that's great! regarding the release, don't worry we can wait for your release, we already have a version up in the AppStore, I found this issue while reworking the presentation layer of the module in our project that is in charge of presenting the Atomic flow, so it's definitely not a blocker right now, just a good to have so we can get rid of the retain cycle. 

Thanks again for working on this super fast 🙌

**Comment by sean-hill** [comment]
@GianniCarlo FINALLY [we have a release](https://github.com/atomicfi/atomic-transact-ios/releases/tag/3.0.6) that should fix this issue 😄 Thanks for your patience!
