### ISSUE TITLE
Xcode 15.3 Invalid Bundle Build Errors Due To Minimum SDK Mismatch

### ISSUE THREAD

**Issue by mccarron** [atomicfi/atomic-transact-ios#2]
There [appears to be a recent change in Xcode 15.3](https://developer.apple.com/forums/thread/705297?answerId=711975022#711975022) that validates Frameworks Info.plist against their binaries. This breaks both`AtomicTransact` and `AtomicTransactSwiftUI` from being used when submitting to Apple when using Xcode 15.3.

```
[11:07:32]: Asset validation failed Invalid Bundle. 
The bundle client.app/Frameworks/AtomicTransact.framework does not support the minimum 
OS Version specified in the Info.plist. 

[11:07:32]: Asset validation failed Invalid Bundle. 
The bundle client.app/Frameworks/AtomicTransactSwiftUI.framework does not support the minimum 
OS Version specified in the Info.plist.
```

Appears the binary is set to a **minimum of 16.0** and the SDK is **Info.plist is set to 10.0**.

Partial Output of `vtool -show Frameworks/AtomicTransact.framework/AtomicTransact`
```
Frameworks/AtomicTransact.framework/AtomicTransact:
    minos 16.0
      sdk 17.4
```

Partial Contents of Frameworks/AtomicTransact.frameworkInfo.plist
```
<key>MinimumOSVersion</key>
<string>10.0</string>
```

**Comment by Tr3yb0** [comment]
Thanks for bringing this to us @mccarron and apologies for any inconvenience! 
We will have our mobile team take a look and provide a solution as soon as we can.

**Comment by mccarron** [comment]
@Tr3yb0 Thanks we're unable to update our Xcode build system and your SDK until this is resolved.
